
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-11T14:30:47.395+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoRegisterCustomerWebServiceImplService",
                      portName = "DoRegisterCustomerWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/DoRegisterCustomerWebService.wsdl",
                      endpointInterface = "com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService.DoRegisterCustomerWebService")
                      
public class DoRegisterCustomerWebServiceImpl implements DoRegisterCustomerWebService {

    private static final Logger LOG = Logger.getLogger(DoRegisterCustomerWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService.DoRegisterCustomerWebService#registerCustomer(com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService.RegCustRequestDTO  arg0 )*
     */
    public com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService.RegCustResponseDTO registerCustomer(com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService.RegCustRequestDTO arg0) { 
        LOG.info("Executing operation registerCustomer");
        System.out.println(arg0);
        try {
            com.infohold.cms.adapter.ecif.DoRegisterCustomerWebService.RegCustResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
