
package ecif.QueryPerCustInfo360WebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:37.734+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class QueryPerCustInfo360WebService_QueryPerCustInfo360WebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.service.ecif.infohold.com/", "QueryPerCustInfo360WebServiceImplService");

    private QueryPerCustInfo360WebService_QueryPerCustInfo360WebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueryPerCustInfo360WebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryPerCustInfo360WebServiceImplService ss = new QueryPerCustInfo360WebServiceImplService(wsdlURL, SERVICE_NAME);
        QueryPerCustInfo360WebService port = ss.getQueryPerCustInfo360WebServiceImplPort();  
        
        {
        System.out.println("Invoking queryPerCustInfo360...");
        ecif.QueryPerCustInfo360WebService.QueryPerCust360RequestDTO _queryPerCustInfo360_arg0 = null;
        ecif.QueryPerCustInfo360WebService.QueryPerCust360ResponseDTO _queryPerCustInfo360__return = port.queryPerCustInfo360(_queryPerCustInfo360_arg0);
        System.out.println("queryPerCustInfo360.result=" + _queryPerCustInfo360__return);


        }

        System.exit(0);
    }

}
