
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ecif.DoUpdatePerCustWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:48:02.255+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoUpdatePerCustWebServiceImplService",
                      portName = "DoUpdatePerCustWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/DoUpdatePerCustWebService.wsdl",
                      endpointInterface = "ecif.DoUpdatePerCustWebService.DoUpdatePerCustWebService")
                      
public class DoUpdatePerCustWebServiceImpl implements DoUpdatePerCustWebService {

    private static final Logger LOG = Logger.getLogger(DoUpdatePerCustWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ecif.DoUpdatePerCustWebService.DoUpdatePerCustWebService#doUpdatePerCustInfo(ecif.DoUpdatePerCustWebService.DoUpdatePerCustRequestDTO  arg0 )*
     */
    public ecif.DoUpdatePerCustWebService.DoUpdatePerCustResponseDTO doUpdatePerCustInfo(ecif.DoUpdatePerCustWebService.DoUpdatePerCustRequestDTO arg0) { 
        LOG.info("Executing operation doUpdatePerCustInfo");
        System.out.println(arg0);
        try {
            ecif.DoUpdatePerCustWebService.DoUpdatePerCustResponseDTO _return = new ecif.DoUpdatePerCustWebService.DoUpdatePerCustResponseDTO();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
