package ecif.DoUpdatePerCustWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:48:02.311+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.service.ecif.infohold.com/", name = "DoUpdatePerCustWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DoUpdatePerCustWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "do_updatePerCustInfo", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoUpdatePerCustWebService.DoUpdatePerCustInfo")
    @WebMethod(operationName = "do_updatePerCustInfo")
    @ResponseWrapper(localName = "do_updatePerCustInfoResponse", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoUpdatePerCustWebService.DoUpdatePerCustInfoResponse")
    public ecif.DoUpdatePerCustWebService.DoUpdatePerCustResponseDTO doUpdatePerCustInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        ecif.DoUpdatePerCustWebService.DoUpdatePerCustRequestDTO arg0
    );
}
