package ecif.DoUpdatePerCustWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:48:02.322+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "DoUpdatePerCustWebServiceImplService", 
                  wsdlLocation = "file:wsdl/DoUpdatePerCustWebService.wsdl",
                  targetNamespace = "http://impl.webservice.service.ecif.infohold.com/") 
public class DoUpdatePerCustWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoUpdatePerCustWebServiceImplService");
    public final static QName DoUpdatePerCustWebServiceImplPort = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoUpdatePerCustWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/DoUpdatePerCustWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoUpdatePerCustWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:wsdl/DoUpdatePerCustWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoUpdatePerCustWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoUpdatePerCustWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoUpdatePerCustWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DoUpdatePerCustWebService
     */
    @WebEndpoint(name = "DoUpdatePerCustWebServiceImplPort")
    public DoUpdatePerCustWebService getDoUpdatePerCustWebServiceImplPort() {
        return super.getPort(DoUpdatePerCustWebServiceImplPort, DoUpdatePerCustWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoUpdatePerCustWebService
     */
    @WebEndpoint(name = "DoUpdatePerCustWebServiceImplPort")
    public DoUpdatePerCustWebService getDoUpdatePerCustWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DoUpdatePerCustWebServiceImplPort, DoUpdatePerCustWebService.class, features);
    }

}
