package ecif.DoUpdateCustomerPwdWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:05.480+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.service.ecif.infohold.com/", name = "DoUpdateCustomerPwdWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DoUpdateCustomerPwdWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "do_updateCustomerPwd", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoUpdateCustomerPwdWebService.DoUpdateCustomerPwd")
    @WebMethod(operationName = "do_updateCustomerPwd")
    @ResponseWrapper(localName = "do_updateCustomerPwdResponse", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoUpdateCustomerPwdWebService.DoUpdateCustomerPwdResponse")
    public ecif.DoUpdateCustomerPwdWebService.UpdateCustomerPwdResponseDTO doUpdateCustomerPwd(
        @WebParam(name = "arg0", targetNamespace = "")
        ecif.DoUpdateCustomerPwdWebService.UpdateCustomerPwdRequestDTO arg0
    );
}
