package ecif.DoUpdateCustomerPwdWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:05.489+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "DoUpdateCustomerPwdWebServiceImplService", 
                  wsdlLocation = "file:wsdl/DoUpdateCustomerPwdWebService.wsdl",
                  targetNamespace = "http://impl.webservice.service.ecif.infohold.com/") 
public class DoUpdateCustomerPwdWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoUpdateCustomerPwdWebServiceImplService");
    public final static QName DoUpdateCustomerPwdWebServiceImplPort = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoUpdateCustomerPwdWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/DoUpdateCustomerPwdWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoUpdateCustomerPwdWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:wsdl/DoUpdateCustomerPwdWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoUpdateCustomerPwdWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoUpdateCustomerPwdWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoUpdateCustomerPwdWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DoUpdateCustomerPwdWebService
     */
    @WebEndpoint(name = "DoUpdateCustomerPwdWebServiceImplPort")
    public DoUpdateCustomerPwdWebService getDoUpdateCustomerPwdWebServiceImplPort() {
        return super.getPort(DoUpdateCustomerPwdWebServiceImplPort, DoUpdateCustomerPwdWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoUpdateCustomerPwdWebService
     */
    @WebEndpoint(name = "DoUpdateCustomerPwdWebServiceImplPort")
    public DoUpdateCustomerPwdWebService getDoUpdateCustomerPwdWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DoUpdateCustomerPwdWebServiceImplPort, DoUpdateCustomerPwdWebService.class, features);
    }

}
