
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ecif.DoUpdateCustomerPwdWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:05.469+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoUpdateCustomerPwdWebServiceImplService",
                      portName = "DoUpdateCustomerPwdWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/DoUpdateCustomerPwdWebService.wsdl",
                      endpointInterface = "ecif.DoUpdateCustomerPwdWebService.DoUpdateCustomerPwdWebService")
                      
public class DoUpdateCustomerPwdWebServiceImpl implements DoUpdateCustomerPwdWebService {

    private static final Logger LOG = Logger.getLogger(DoUpdateCustomerPwdWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ecif.DoUpdateCustomerPwdWebService.DoUpdateCustomerPwdWebService#doUpdateCustomerPwd(ecif.DoUpdateCustomerPwdWebService.UpdateCustomerPwdRequestDTO  arg0 )*
     */
    public ecif.DoUpdateCustomerPwdWebService.UpdateCustomerPwdResponseDTO doUpdateCustomerPwd(ecif.DoUpdateCustomerPwdWebService.UpdateCustomerPwdRequestDTO arg0) { 
        LOG.info("Executing operation doUpdateCustomerPwd");
        System.out.println(arg0);
        try {
            ecif.DoUpdateCustomerPwdWebService.UpdateCustomerPwdResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
