
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ecif.SetSecurityQuestionWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:59.735+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "SetSecurityQuestionWebServiceImplService",
                      portName = "SetSecurityQuestionWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/SetSecurityQuestionWebService.wsdl",
                      endpointInterface = "ecif.SetSecurityQuestionWebService.SetSecurityQuestionWebService")
                      
public class SetSecurityQuestionWebServiceImpl implements SetSecurityQuestionWebService {

    private static final Logger LOG = Logger.getLogger(SetSecurityQuestionWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ecif.SetSecurityQuestionWebService.SetSecurityQuestionWebService#setSecurityQuestion(ecif.SetSecurityQuestionWebService.SetSecurityQuestionRequestDTO  arg0 )*
     */
    public ecif.SetSecurityQuestionWebService.SetSecurityQuestionResponseDTO setSecurityQuestion(ecif.SetSecurityQuestionWebService.SetSecurityQuestionRequestDTO arg0) { 
        LOG.info("Executing operation setSecurityQuestion");
        System.out.println(arg0);
        try {
            ecif.SetSecurityQuestionWebService.SetSecurityQuestionResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
