package ecif.SetSecurityQuestionWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:59.748+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.service.ecif.infohold.com/", name = "SetSecurityQuestionWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface SetSecurityQuestionWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "set_securityQuestion", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.SetSecurityQuestionWebService.SetSecurityQuestion")
    @WebMethod(operationName = "set_securityQuestion")
    @ResponseWrapper(localName = "set_securityQuestionResponse", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.SetSecurityQuestionWebService.SetSecurityQuestionResponse")
    public ecif.SetSecurityQuestionWebService.SetSecurityQuestionResponseDTO setSecurityQuestion(
        @WebParam(name = "arg0", targetNamespace = "")
        ecif.SetSecurityQuestionWebService.SetSecurityQuestionRequestDTO arg0
    );
}
