
package ecif.SetSecurityQuestionWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:16:59.625+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class SetSecurityQuestionWebService_SetSecurityQuestionWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.service.ecif.infohold.com/", "SetSecurityQuestionWebServiceImplService");

    private SetSecurityQuestionWebService_SetSecurityQuestionWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SetSecurityQuestionWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SetSecurityQuestionWebServiceImplService ss = new SetSecurityQuestionWebServiceImplService(wsdlURL, SERVICE_NAME);
        SetSecurityQuestionWebService port = ss.getSetSecurityQuestionWebServiceImplPort();  
        
        {
        System.out.println("Invoking setSecurityQuestion...");
        ecif.SetSecurityQuestionWebService.SetSecurityQuestionRequestDTO _setSecurityQuestion_arg0 = null;
        ecif.SetSecurityQuestionWebService.SetSecurityQuestionResponseDTO _setSecurityQuestion__return = port.setSecurityQuestion(_setSecurityQuestion_arg0);
        System.out.println("setSecurityQuestion.result=" + _setSecurityQuestion__return);


        }

        System.exit(0);
    }

}
