package ecif.DoRegisterCustomerWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-10-10T14:16:06.866+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.service.ecif.infohold.com/", name = "DoRegisterCustomerWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DoRegisterCustomerWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerCustomer", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoRegisterCustomerWebService.RegisterCustomer")
    @WebMethod
    @ResponseWrapper(localName = "registerCustomerResponse", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoRegisterCustomerWebService.RegisterCustomerResponse")
    public ecif.DoRegisterCustomerWebService.RegCustResponseDTO registerCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        ecif.DoRegisterCustomerWebService.RegCustRequestDTO arg0
    );
}
