package ecif.DoRegisterCustomerWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-10-10T14:16:06.892+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "DoRegisterCustomerWebServiceImplService", 
                  wsdlLocation = "file:wsdl/DoRegisterCustomerWebService.wsdl",
                  targetNamespace = "http://impl.webservice.service.ecif.infohold.com/") 
public class DoRegisterCustomerWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoRegisterCustomerWebServiceImplService");
    public final static QName DoRegisterCustomerWebServiceImplPort = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoRegisterCustomerWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/DoRegisterCustomerWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DoRegisterCustomerWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:wsdl/DoRegisterCustomerWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DoRegisterCustomerWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DoRegisterCustomerWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoRegisterCustomerWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DoRegisterCustomerWebService
     */
    @WebEndpoint(name = "DoRegisterCustomerWebServiceImplPort")
    public DoRegisterCustomerWebService getDoRegisterCustomerWebServiceImplPort() {
        return super.getPort(DoRegisterCustomerWebServiceImplPort, DoRegisterCustomerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoRegisterCustomerWebService
     */
    @WebEndpoint(name = "DoRegisterCustomerWebServiceImplPort")
    public DoRegisterCustomerWebService getDoRegisterCustomerWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DoRegisterCustomerWebServiceImplPort, DoRegisterCustomerWebService.class, features);
    }

}
