
package ecif.DoRegisterCustomerWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-10-10T14:16:06.548+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class DoRegisterCustomerWebService_DoRegisterCustomerWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.service.ecif.infohold.com/", "DoRegisterCustomerWebServiceImplService");

    private DoRegisterCustomerWebService_DoRegisterCustomerWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DoRegisterCustomerWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DoRegisterCustomerWebServiceImplService ss = new DoRegisterCustomerWebServiceImplService(wsdlURL, SERVICE_NAME);
        DoRegisterCustomerWebService port = ss.getDoRegisterCustomerWebServiceImplPort();  
        
        {
        System.out.println("Invoking registerCustomer...");
        ecif.DoRegisterCustomerWebService.RegCustRequestDTO _registerCustomer_arg0 = new ecif.DoRegisterCustomerWebService.RegCustRequestDTO();
        ecif.DoRegisterCustomerWebService.RegCustResponseDTO _registerCustomer__return = port.registerCustomer(_registerCustomer_arg0);
        System.out.println("registerCustomer.result=" + _registerCustomer__return);


        }

        System.exit(0);
    }

}
