
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ecif.DoRegisterCustomerWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-10-10T14:16:06.823+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoRegisterCustomerWebServiceImplService",
                      portName = "DoRegisterCustomerWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/DoRegisterCustomerWebService.wsdl",
                      endpointInterface = "ecif.DoRegisterCustomerWebService.DoRegisterCustomerWebService")
                      
public class DoRegisterCustomerWebServiceImpl implements DoRegisterCustomerWebService {

    private static final Logger LOG = Logger.getLogger(DoRegisterCustomerWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ecif.DoRegisterCustomerWebService.DoRegisterCustomerWebService#registerCustomer(ecif.DoRegisterCustomerWebService.RegCustRequestDTO  arg0 )*
     */
    public ecif.DoRegisterCustomerWebService.RegCustResponseDTO registerCustomer(ecif.DoRegisterCustomerWebService.RegCustRequestDTO arg0) { 
        LOG.info("Executing operation registerCustomer");
        System.out.println(arg0);
        try {
            ecif.DoRegisterCustomerWebService.RegCustResponseDTO _return = new ecif.DoRegisterCustomerWebService.RegCustResponseDTO();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
