<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.webservice.service.ecif.infohold.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://webservice.service.ecif.infohold.com/" name="DoUpdateCustomerPwdWebServiceImplService" targetNamespace="http://impl.webservice.service.ecif.infohold.com/">
  <wsdl:import location="http://192.168.20.15:8080/com.infohold.ecif.service/ws/DoUpdateCustomerPwdWebService?wsdl=DoUpdateCustomerPwdWebService.wsdl" namespace="http://webservice.service.ecif.infohold.com/">
    </wsdl:import>
  <wsdl:binding name="DoUpdateCustomerPwdWebServiceImplServiceSoapBinding" type="ns1:DoUpdateCustomerPwdWebService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="do_updateCustomerPwd">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="do_updateCustomerPwd">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="do_updateCustomerPwdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="DoUpdateCustomerPwdWebServiceImplService">
    <wsdl:port binding="tns:DoUpdateCustomerPwdWebServiceImplServiceSoapBinding" name="DoUpdateCustomerPwdWebServiceImplPort">
      <soap:address location="http://192.168.20.15:8080/com.infohold.ecif.service/ws/DoUpdateCustomerPwdWebService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>