
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ecif.DoSecurityQuestionWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:15:35.141+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "DoSecurityQuestionWebServiceImplService",
                      portName = "DoSecurityQuestionWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/DoSecurityQuestionWebService.wsdl",
                      endpointInterface = "ecif.DoSecurityQuestionWebService.DoSecurityQuestionWebService")
                      
public class DoSecurityQuestionWebServiceImpl implements DoSecurityQuestionWebService {

    private static final Logger LOG = Logger.getLogger(DoSecurityQuestionWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ecif.DoSecurityQuestionWebService.DoSecurityQuestionWebService#doSecurityQuestion(ecif.DoSecurityQuestionWebService.DoSecurityQuestionRequestDTO  arg0 )*
     */
    public ecif.DoSecurityQuestionWebService.DoSecurityQuestionResponseDTO doSecurityQuestion(ecif.DoSecurityQuestionWebService.DoSecurityQuestionRequestDTO arg0) { 
        LOG.info("Executing operation doSecurityQuestion");
        System.out.println(arg0);
        try {
            ecif.DoSecurityQuestionWebService.DoSecurityQuestionResponseDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
