package ecif.DoSecurityQuestionWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-19T11:15:35.152+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.service.ecif.infohold.com/", name = "DoSecurityQuestionWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DoSecurityQuestionWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "do_securityQuestion", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoSecurityQuestionWebService.DoSecurityQuestion")
    @WebMethod(operationName = "do_securityQuestion")
    @ResponseWrapper(localName = "do_securityQuestionResponse", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.DoSecurityQuestionWebService.DoSecurityQuestionResponse")
    public ecif.DoSecurityQuestionWebService.DoSecurityQuestionResponseDTO doSecurityQuestion(
        @WebParam(name = "arg0", targetNamespace = "")
        ecif.DoSecurityQuestionWebService.DoSecurityQuestionRequestDTO arg0
    );
}
