package ecif.QueryPerCustInfoWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:47:16.624+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://webservice.service.ecif.infohold.com/", name = "QueryPerCustInfoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryPerCustInfoWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "query_perCustInfo", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.QueryPerCustInfoWebService.QueryPerCustInfo")
    @WebMethod(operationName = "query_perCustInfo")
    @ResponseWrapper(localName = "query_perCustInfoResponse", targetNamespace = "http://webservice.service.ecif.infohold.com/", className = "ecif.QueryPerCustInfoWebService.QueryPerCustInfoResponse")
    public ecif.QueryPerCustInfoWebService.QueryPerCustResponseDTO queryPerCustInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        ecif.QueryPerCustInfoWebService.QueryPerCustRequestDTO arg0
    );
}
