package ecif.QueryPerCustInfoWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:47:16.631+08:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "QueryPerCustInfoWebServiceImplService", 
                  wsdlLocation = "file:wsdl/QueryPerCustInfoWebService.wsdl",
                  targetNamespace = "http://impl.webservice.service.ecif.infohold.com/") 
public class QueryPerCustInfoWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.service.ecif.infohold.com/", "QueryPerCustInfoWebServiceImplService");
    public final static QName QueryPerCustInfoWebServiceImplPort = new QName("http://impl.webservice.service.ecif.infohold.com/", "QueryPerCustInfoWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/QueryPerCustInfoWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryPerCustInfoWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:wsdl/QueryPerCustInfoWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryPerCustInfoWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryPerCustInfoWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryPerCustInfoWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QueryPerCustInfoWebService
     */
    @WebEndpoint(name = "QueryPerCustInfoWebServiceImplPort")
    public QueryPerCustInfoWebService getQueryPerCustInfoWebServiceImplPort() {
        return super.getPort(QueryPerCustInfoWebServiceImplPort, QueryPerCustInfoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryPerCustInfoWebService
     */
    @WebEndpoint(name = "QueryPerCustInfoWebServiceImplPort")
    public QueryPerCustInfoWebService getQueryPerCustInfoWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(QueryPerCustInfoWebServiceImplPort, QueryPerCustInfoWebService.class, features);
    }

}
