
package ecif.QueryPerCustInfoWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:47:16.393+08:00
 * Generated source version: 2.7.4
 * 
 */
public final class QueryPerCustInfoWebService_QueryPerCustInfoWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.service.ecif.infohold.com/", "QueryPerCustInfoWebServiceImplService");

    private QueryPerCustInfoWebService_QueryPerCustInfoWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueryPerCustInfoWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryPerCustInfoWebServiceImplService ss = new QueryPerCustInfoWebServiceImplService(wsdlURL, SERVICE_NAME);
        QueryPerCustInfoWebService port = ss.getQueryPerCustInfoWebServiceImplPort();  
        
        {
        System.out.println("Invoking queryPerCustInfo...");
        ecif.QueryPerCustInfoWebService.QueryPerCustRequestDTO _queryPerCustInfo_arg0 = new ecif.QueryPerCustInfoWebService.QueryPerCustRequestDTO();
        ecif.QueryPerCustInfoWebService.QueryPerCustResponseDTO _queryPerCustInfo__return = port.queryPerCustInfo(_queryPerCustInfo_arg0);
        System.out.println("queryPerCustInfo.result=" + _queryPerCustInfo__return);


        }

        System.exit(0);
    }

}
