
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ecif.QueryPerCustInfoWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2015-08-27T09:47:16.604+08:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "QueryPerCustInfoWebServiceImplService",
                      portName = "QueryPerCustInfoWebServiceImplPort",
                      targetNamespace = "http://impl.webservice.service.ecif.infohold.com/",
                      wsdlLocation = "file:wsdl/QueryPerCustInfoWebService.wsdl",
                      endpointInterface = "ecif.QueryPerCustInfoWebService.QueryPerCustInfoWebService")
                      
public class QueryPerCustInfoWebServiceImpl implements QueryPerCustInfoWebService {

    private static final Logger LOG = Logger.getLogger(QueryPerCustInfoWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ecif.QueryPerCustInfoWebService.QueryPerCustInfoWebService#queryPerCustInfo(ecif.QueryPerCustInfoWebService.QueryPerCustRequestDTO  arg0 )*
     */
    public ecif.QueryPerCustInfoWebService.QueryPerCustResponseDTO queryPerCustInfo(ecif.QueryPerCustInfoWebService.QueryPerCustRequestDTO arg0) { 
        LOG.info("Executing operation queryPerCustInfo");
        System.out.println(arg0);
        try {
            ecif.QueryPerCustInfoWebService.QueryPerCustResponseDTO _return = new ecif.QueryPerCustInfoWebService.QueryPerCustResponseDTO();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
